import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <h1>
                    <Link href="/">Web</Link>
                </h1>
                <input type="text" placeholder="검색" />
                <ol>
                    <li>
                        <Link href="/read/1">html</Link>
                    </li>
                    <li>
                        <Link href="/read/2">css</Link>
                    </li>
                </ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">create</Link>
                    </li>
                    <li>
                        <Link href="/update/id">update</Link>
                    </li>
                    <li>
                        <button>delete</button>
                    </li>
                </ul>
            </body>
        </html>
    );
}
