import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Control } from "@/Control";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const resp = await fetch("http://localhost:9999/topics");
    const topics = await resp.json();
    console.log("🚀 ~ topics:", topics);
    const tags = topics.map((item: { id: string; title: string }) => {
        return (
            <li key={item.id}>
                <Link href={"/read/" + item.id}>{item.title}</Link>
            </li>
        );
    });
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <h1>
                    <Link href="/">Web</Link>
                </h1>
                <input type="text" placeholder="검색" />
                <ol>{tags}</ol>
                {children}
                <ul>
                    <li>
                        <Link href="/create">create</Link>
                    </li>
                    <Control />
                </ul>
            </body>
        </html>
    );
}
